#!/bin/sh
cd "${0%/*}" || exit
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"
runApplication blockMesh
runApplication checkMesh
runApplication setFields
runApplication decomposePar
mpirun --allow-run-as-root -np 4 interFoam -parallel
runApplication reconstructPar
runApplication foamToVTK
